# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://jhonchahuaj.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jhon Chahua
# Description of the Site
description: Servicios de consultoría especializada
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://github.com/JhonChahuaJ/images_page/blob/main/_img/fondo_ch.jpg?raw=true

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: chahua.evar@gmail.com
facebook_username: thedevslot
twitter_username: thedevslot
instagram_username: thedevslot
linkedin_username: thedevslot
github_username:  thedevslot
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Jhon E.

# Name of the Author
author-name: Jhon Chahua
# URL for the Image of the Author
author-image: https://github.com/JhonChahuaJ/images_page/blob/main/_img/pfunir.jpg?raw=true
# 60 Words About the Author
author-about: Especialista en Gestión del Riesgo de Desastres, manejo de modelos numéricos para la simulación de eventos hidrometeorológicos y de movimientos. Implementación de nuevas tecnologías aplicado a estudios de ingeniería.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://jhonchahuaj.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
