# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://jhonchahuaj.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jhon Chahua
# Description of the Site
description: Servicios de consultoría especializada
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://github.com/JhonChahuaJ/images_page/blob/main/_img/fondo_ch.jpg?raw=true

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: chahua.evar@gmail.com
facebook_username: jhon.chahua.902
twitter_username: JhonChahua2
instagram_username: jhelchja
linkedin_username: jhon-elvis-chahua-janampa-5812218b
github_username: JhonChahuaJ 
youtube_channel_id: UCcfdu0Uu671enw7o3TN7E8Q

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: Jhon E.

# Name of the Author
author-name: Jhon E. Chahua Janampa
# URL for the Image of the Author
author-image: https://github.com/JhonChahuaJ/images_page/blob/main/_img/pfunir.jpg?raw=true
# 60 Words About the Author
author-about: Ingeniero Mecánico de Fluidos; especialista en estudios, metodologías y tecnologías en Gestión del Riesgo de Desastres; Manejo de modelos numéricos para la simulación de eventos hidrometeorológicos extremos, movimientos en masa, sísmicos y volcánicos.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://jhonchahuaj.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
